language: node_js
node_js:
  - "8"

branches:
  only:
  - /^prototype-v0.7.0-.*$/

before_install:
  - npm install -g serverless
  - npm install -g @angular/cli
  - sudo apt-get install python3
  - sudo pip install awscli
  - (cd api; openssl aes-256-cbc -K $encrypted_11dfe2bc5063_key -iv $encrypted_11dfe2bc5063_iv -in dashboardhub.pem.enc -out dashboardhub.pem -d)

install:
  - make install

script:
  - echo 'No tests, this is a PROTOTYPE only'

after_success:
  - make deploy
